### ISSUE TITLE
Use Cloud SQL as a database to store data externally

### ISSUE THREAD

**Issue by EZFRICA** [CitizenLabDotCo/citizenlab-docker#9]
In case you want to use an external database for your application, you can use [CLoud SQL](https://cloud.google.com/sql/docs/postgres/connect-docker). You just need to replace this configuration with:

```
  postgres:
    image: "postgis/postgis:12-3.1"
    volumes:
      - "./postgresql-data:/var/lib/postgresql/data"
    env_file:
      - ".env"
```

with 

 ```
 postgres:
    container_name: cloud-sql-proxy
    image: gcr.io/cloudsql-docker/gce-proxy:1.23.1
    volumes:
      - ./ServiceAccount.json:/config
    ports:
      - 127.0.0.1:5432:5432
    command: "/cloud_sql_proxy -instances=myproject:region:myinstance=tcp:0.0.0.0:5432 -credential_file=/config"
    restart: unless-stopped
```

Don't forget to create a service account and give it the Cloud SQL Client role.
